language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
script:
  - "cd android/LockReact/android/ && ./gradlew clean test --continue"
branches:
  only:
  - master
