language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
env:
  - TERM=dumb
before_script:
  - cd "android/LockReact/android"
script:
  - ./gradlew clean :lock-react:test --continue
branches:
  only:
  - master
